name: infra_preparation
description: "Prepare backend configuration and configure OpenTofu version to use"

inputs:
  version: 
    description: "The version of OpenTofu to use"
    default: "1.9.0"
    required: false

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: Enable Backend
    run: cp infrastructure/backend.tf.disabled infrastructure/backend.tf
    shell: bash
  - name: Configure Backend
    run: |
      echo "ARM_AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
      echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
      echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    shell: bash

  - name: Configure OpenTofu
    run: echo "OPENTOFU_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
    shell: bash