name: Remove PR environment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  close_pull_request_job:
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Prepare OpenTofu
        uses: ./.github/actions/infra_preparation
      - name: terraform output
        id: tfoutputs
        uses: dflook/terraform-output@v1
        with:
          path: infrastructure
        env:
          OPENTOFU_VERSION: 1.9.0
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.tfoutputs.outputs.static_web_app_api_key }}
          action: "close"