name: Remove PR environment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  close_pull_request_job:
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: prd
    permissions: 
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare OpenTofu
        uses: ./.github/actions/infra_preparation
        with:
          client-id: "${{ vars.AZURE_CLIENT_ID }}"
          tenant-id: "${{ vars.AZURE_TENANT_ID }}"
          subscription-id: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      - name: terraform output
        id: tfoutputs
        uses: dflook/terraform-output@v1
        with:
          path: infrastructure
          backend_config: |
            resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}
            storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}
            container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.tfoutputs.outputs.static_web_app_api_key }}
          action: "close"